### ISSUE TITLE
Snapshots url down

### ISSUE THREAD

**Issue by Loopingo** [archmac/www#1]
Hello,

Url to download snapshot is down, possible to have new one please?

https://github.com/archmac/www/blob/9c003a0aac6ef98245dd984aaeeb5563751aea47/index.html#L26

Thanks,

**Comment by lloeki** [comment]
Hey, I had to pull the plug on DigitalOcean CDN hosting. I have an archive, I'll see what I can do.

**Comment by lloeki** [comment]
It's up again!
